# Generated by Django 4.2.16 on 2024-09-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentif', '0002_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
