# Generated by Django 4.2.16 on 2024-09-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentif', '0005_user_city_user_country_user_defeats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
